### ISSUE TITLE
What is the difference to https://h2o.ai/ ?

### ISSUE THREAD

**Issue by timmwille** [stevegt/grokker#2]
I like the Open Source approaches popping up everywhere, though I also see a lot of double work maybe not needed. 

Maybe you can check this example and tell a bit about the differences?

**Comment by stevegt** [comment]
Grokker is bootstrap tooling for [PromiseGrid](https://github.com/promisegrid/promisegrid).  Also see https://github.com/stevegt/grokker#roadmap.
